### ISSUE TITLE
Application fails to start: missing newrelic.ini

### ISSUE THREAD

**Issue by jtesta** [UnrealAkama/NightShade#4]
$ gunicorn -b 0.0.0.0:8080 NightShade.wsgi
[2017-02-19 18:09:13 +0000] [2721] [INFO] Starting gunicorn 19.3.0
[2017-02-19 18:09:13 +0000] [2721] [INFO] Listening at: http://0.0.0.0:8080 (2721)
[2017-02-19 18:09:13 +0000] [2721] [INFO] Using worker: sync
[2017-02-19 18:09:13 +0000] [2726] [INFO] Booting worker with pid: 2726
[2017-02-19 18:09:13 +0000] [2726] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/var/www/NightShade/NightShade/wsgi.py", line 20, in <module>
    newrelic.agent.initialize('newrelic.ini')
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.64.0.48/newrelic/config.py", line 2526, in initialize
    log_file, log_level)
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.64.0.48/newrelic/config.py", line 845, in _load_configuration
    'Unable to open configuration file %s.' % config_file)
ConfigurationError: Unable to open configuration file newrelic.ini.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 507, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 118, in init_process
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/util.py", line 355, in import_app
    __import__(module)
  File "/var/www/NightShade/NightShade/wsgi.py", line 20, in <module>
    newrelic.agent.initialize('newrelic.ini')
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.64.0.48/newrelic/config.py", line 2526, in initialize
    log_file, log_level)
  File "/usr/local/lib/python2.7/dist-packages/newrelic-2.64.0.48/newrelic/config.py", line 845, in _load_configuration
    'Unable to open configuration file %s.' % config_file)
ConfigurationError: Unable to open configuration file newrelic.ini.
[2017-02-19 18:09:13 +0000] [2726] [INFO] Worker exiting (pid: 2726)
[2017-02-19 18:09:13 +0000] [2721] [INFO] Shutting down: Master
[2017-02-19 18:09:13 +0000] [2721] [INFO] Reason: Worker failed to boot.

**Comment by incertia** [comment]
```
touch newrelic.ini
```

**Comment by jtesta** [comment]
Thanks for the response.  Unfortunately, since it didn't work right out of the box, I had to pass up NightShade in favor of CTFd.
