### ISSUE TITLE
[Question] NightShade without AWS

### ISSUE THREAD

**Issue by noraj1337** [UnrealAkama/NightShade#5]
What if we want to install it our own server (without amazon):

```
$ python2 manage.py migrate_schemas --shared
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python2.7/site-packages/django/core/management/__init__.py", line 316, in execute
    settings.INSTALLED_APPS
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 53, in __getattr__
    self._setup(name)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "/usr/lib/python2.7/site-packages/django/conf/__init__.py", line 97, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/noraj/NightShade/NightShade/settings.py", line 215, in <module>
    AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
  File "/usr/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'AWS_ACCESS_KEY_ID'
```

Can I remove all AWS variable, use `https://localhost` or whatever as `MEDIA_URL` and a local relativ path for `DEFAULT_FILE_STORAGE`?

```
$ tail -7 NightShade/settings.py
AWS_STORAGE_BUCKET_NAME = 'nightshade-files'
AWS_ACCESS_KEY_ID = os.environ['AWS_ACCESS_KEY_ID']
AWS_SECRET_ACCESS_KEY = os.environ['AWS_SECRET_ACCESS_KEY']
AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

MEDIA_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto.S3BotoStorage'
```

**Comment by inutza** [comment]
+1 I'd be interested in the solution for this problem as well.

**Comment by kristoffer-marshall** [comment]
Same here. Nowhere did the documentation mention AWS. I've seen this code in action before, and I thought it was being hosted in-house, but now I'm not sure. I did a checkout on an older version, but no luck still.

**Comment by noraj** [comment]
@kristoffer-marshall You can find a CTF platform that better fit your need [here](http://list.rawsec.ml/ctf_platforms.html).
